### ISSUE TITLE
step fails when variable names are long

### ISSUE THREAD

**Issue by smyth7** [runehaubo/lmerTestR#13] opened 2018-07-25 11:29 UTC
Hi,

I find that step.lmerModLmerTest fails at some point when there are variables with 'long' names and their interactions. Renaming variables to one character and repeating works fine. In my example I had 10 variables plus their interactions.

Paul

**Comment by runehaubo** [comment] 2018-08-02 12:18
Thanks for the report. The restriction is due to `deparse` which has a `500L` characters limit. On the top of my head I don't see a way to circumvent this, but pull requests are always welcome.

**Comment by runehaubo** [comment] 2020-10-19 17:46
I think we have this fixed now using af safer `deparse`ing but without a reproducible example I'm not sure.

**Closed by runehaubo** 2020-10-19 17:46 UTC
